# .streamlit/secrets.toml

# Replace "YOUR_API_KEY" with your actual Gemini API key
GEMINI_API_KEY = "YOUR_API_KEY"

# data.gov.in API Key for Market Prices
DATA_GOV_IN_API_KEY = "579b464db66ec23bdd000001fe27abc1a0854afd78d0d20e9d06b6c5"

# AssemblyAI API Key for Speech-to-Text
ASSEMBLYAI_API_KEY = "55de22742c8045d482a71ce6f648a732"
